export const CATEGORY_ACTIONS = {
  CREATE_PRODUCT_CATEGORY: 'CREATE_PRODUCT_CATEGORY',
  CREATE_SERVICE_CATEGORY: 'CREATE_SERVICE_CATEGORY',
  GET_PRODUCT_CATEGORIES: 'GET_PRODUCT_CATEGORIES',
  GET_SERVICE_CATEGORIES: 'GET_SERVICE_CATEGORIES',
}
