const selectActionTypes = {
  SELECT: 'SELECT',
  SELECT_PETIT_STOCK: 'SELECT_PETIT_STOCK',
  SELECT_STOCK_ITEM: 'SELECT_STOCK_ITEM',
  SELECT_STORE: 'SELECT_STORE',
  SELECT_EVENT_SHEET: 'SELECT_EVENT_SHEET',
}
export default selectActionTypes
